from BaseClasses import Location

class GDLocation(Location):
    game: str = "Geometry Dash"

gd_base_id = 130820130

location_table = {
    "Stereo Madness": 0 + gd_base_id,
    "Back On Track": 1 + gd_base_id,
    "Polargeist": 2 + gd_base_id,
    "Dry Out": 3 + gd_base_id,
    "Base After Base": 4 + gd_base_id,
    "Cant Let Go": 5 + gd_base_id,
    "Jumper": 6 + gd_base_id,
    "Time Machine": 7 + gd_base_id,
    "Cycles": 8 + gd_base_id,
    "xStep": 9 + gd_base_id,
    "Clutterfunk": 10 + gd_base_id,
    "Theory of Everything": 11 + gd_base_id,
    "Electroman Adventures": 12 + gd_base_id,
    "Clubstep": 13 + gd_base_id,
    "Electrodynamix": 14 + gd_base_id,
    "Hexagon Force": 15 + gd_base_id,
    "Blast Processing": 16 + gd_base_id,
    "Theory of Everything 2": 17 + gd_base_id,
    "Geometrical Dominator": 18 + gd_base_id,
    "Deadlocked": 19 + gd_base_id,
    "Fingerdash": 20 + gd_base_id,
    "Dash": 21 + gd_base_id,
    "The Tower": 22 + gd_base_id,
    "The Sewers": 23 + gd_base_id,
    "The Cellar": 24 + gd_base_id,
    "The Secret Hollow": 25 + gd_base_id,
}

ultimate_locations = {
    "Ultimate Clubstep": 26 + gd_base_id,
    "Ultimate Theory of Everything 2": 27 + gd_base_id,
    "Ultimate Deadlocked": 28 + gd_base_id
}

# unused until MoreGames is ported to 2.2081 (probably wont be so ill just not use this)
spinoff_locations = {
    "The Seven Seas": 29 + gd_base_id,
    "Viking Arena": 30 + gd_base_id,
    "Airborne Robots": 31 + gd_base_id,
    "Press Start": 32 + gd_base_id,
    "Nock Em": 33 + gd_base_id,
    "Power Trip": 34 + gd_base_id,

}

possible_starting_levels = {
    "Stereo Madness": 0 + gd_base_id,
    "Back On Track": 1 + gd_base_id,
    "Polargeist": 2 + gd_base_id,
    "Dry Out": 3 + gd_base_id,
    "Base After Base": 4 + gd_base_id,
    "Cant Let Go": 5 + gd_base_id,
    "Jumper": 6 + gd_base_id,
    "Time Machine": 7 + gd_base_id,
}

check_shop_locations = {
    "Check Shop #1": 100 + gd_base_id,
    "Check Shop #2": 101 + gd_base_id,
    "Check Shop #3": 102 + gd_base_id,
    "Check Shop #4": 103 + gd_base_id,
    "Check Shop #5": 104 + gd_base_id,
    "Check Shop #6": 105 + gd_base_id,
}

coins = { # autogenerated with a script:
#    
#for key in location_table:
#for i in range(3):
#    name = key + " - Coin " + str(i + 1)
#    value = (location_table[key] - gd_base_id) * 1000 + (i + 1) + gd_base_id
#    coins[name] = value
#prnt = str(coins)
#print(prnt.replace(", ", ",\n"))

'Stereo Madness - Coin 1': 1001 + gd_base_id,
'Stereo Madness - Coin 2': 1002 + gd_base_id,
'Stereo Madness - Coin 3': 1003 + gd_base_id,
'Back On Track - Coin 1': 2001 + gd_base_id,
'Back On Track - Coin 2': 2002 + gd_base_id,
'Back On Track - Coin 3': 2003 + gd_base_id,
'Polargeist - Coin 1': 3001 + gd_base_id,
'Polargeist - Coin 2': 3002 + gd_base_id,
'Polargeist - Coin 3': 3003 + gd_base_id,
'Dry Out - Coin 1': 4001 + gd_base_id,
'Dry Out - Coin 2': 4002 + gd_base_id,
'Dry Out - Coin 3': 4003 + gd_base_id,
'Base After Base - Coin 1': 5001 + gd_base_id,
'Base After Base - Coin 2': 5002 + gd_base_id,
'Base After Base - Coin 3': 5003 + gd_base_id,
'Cant Let Go - Coin 1': 6001 + gd_base_id,
'Cant Let Go - Coin 2': 6002 + gd_base_id,
'Cant Let Go - Coin 3': 6003 + gd_base_id,
'Jumper - Coin 1': 7001 + gd_base_id,
'Jumper - Coin 2': 7002 + gd_base_id,
'Jumper - Coin 3': 7003 + gd_base_id,
'Time Machine - Coin 1': 8001 + gd_base_id,
'Time Machine - Coin 2': 8002 + gd_base_id,
'Time Machine - Coin 3': 8003 + gd_base_id,
'Cycles - Coin 1': 9001 + gd_base_id,
'Cycles - Coin 2': 9002 + gd_base_id,
'Cycles - Coin 3': 9003 + gd_base_id,
'xStep - Coin 1': 10001 + gd_base_id,
'xStep - Coin 2': 10002 + gd_base_id,
'xStep - Coin 3': 10003 + gd_base_id,
'Clutterfunk - Coin 1': 11001 + gd_base_id,
'Clutterfunk - Coin 2': 11002 + gd_base_id,
'Clutterfunk - Coin 3': 11003 + gd_base_id,
'Theory of Everything - Coin 1': 12001 + gd_base_id,
'Theory of Everything - Coin 2': 12002 + gd_base_id,
'Theory of Everything - Coin 3': 12003 + gd_base_id,
'Electroman Adventures - Coin 1': 13001 + gd_base_id,
'Electroman Adventures - Coin 2': 13002 + gd_base_id,
'Electroman Adventures - Coin 3': 13003 + gd_base_id,
'Clubstep - Coin 1': 14001 + gd_base_id,
'Clubstep - Coin 2': 14002 + gd_base_id,
'Clubstep - Coin 3': 14003 + gd_base_id,
'Electrodynamix - Coin 1': 15001 + gd_base_id,
'Electrodynamix - Coin 2': 15002 + gd_base_id,
'Electrodynamix - Coin 3': 15003 + gd_base_id,
'Hexagon Force - Coin 1': 16001 + gd_base_id,
'Hexagon Force - Coin 2': 16002 + gd_base_id,
'Hexagon Force - Coin 3': 16003 + gd_base_id,
'Blast Processing - Coin 1': 17001 + gd_base_id,
'Blast Processing - Coin 2': 17002 + gd_base_id,
'Blast Processing - Coin 3': 17003 + gd_base_id,
'Theory of Everything 2 - Coin 1': 18001 + gd_base_id,
'Theory of Everything 2 - Coin 2': 18002 + gd_base_id,
'Theory of Everything 2 - Coin 3': 18003 + gd_base_id,
'Geometrical Dominator - Coin 1': 19001 + gd_base_id,
'Geometrical Dominator - Coin 2': 19002 + gd_base_id,
'Geometrical Dominator - Coin 3': 19003 + gd_base_id,
'Deadlocked - Coin 1': 20001 + gd_base_id,
'Deadlocked - Coin 2': 20002 + gd_base_id,
'Deadlocked - Coin 3': 20003 + gd_base_id,
'Fingerdash - Coin 1': 21001 + gd_base_id,
'Fingerdash - Coin 2': 21002 + gd_base_id,
'Fingerdash - Coin 3': 21003 + gd_base_id,
'Dash - Coin 1': 22001 + gd_base_id,
'Dash - Coin 2': 22002 + gd_base_id,
'Dash - Coin 3': 22003 + gd_base_id,
'The Tower - Coin 1': 23001 + gd_base_id,
'The Tower - Coin 2': 23002 + gd_base_id,
'The Tower - Coin 3': 23003 + gd_base_id,
'The Sewers - Coin 1': 24001 + gd_base_id,
'The Sewers - Coin 2': 24002 + gd_base_id,
'The Sewers - Coin 3': 24003 + gd_base_id,
'The Cellar - Coin 1': 25001 + gd_base_id,
'The Cellar - Coin 2': 25002 + gd_base_id,
'The Cellar - Coin 3': 25003 + gd_base_id,
'The Secret Hollow - Coin 1': 26001 + gd_base_id,
'The Secret Hollow - Coin 2': 26002 + gd_base_id,
'The Secret Hollow - Coin 3': 26003 + gd_base_id
}